-- Director-entered away dates.
--
-- The director sometimes gets told "I'm away that week, can you put it in" and
-- had no way to do it — the Vacation page only ever showed the signed-in
-- person's own card. Row-level security already permitted it (both away-date
-- policies carry is_director_or_admin()), so what was missing was the audit
-- trail and the lookup the picker needs.
--
--   * entered_by on both away-date tables, stamped from the session by a
--     trigger so the client cannot spoof it. A provider can then see that a
--     date they did not add themselves came from the director.
--   * a unique index on fellow_away_dates(fellow_id, away_date), matching the
--     one provider_away_dates already had, so a date range can be upserted
--     idempotently. decide_vacation() already said "on conflict do nothing",
--     which only starts doing anything once this index exists.
--   * away_people() — the picker list: every active fellow, supervisor and
--     director, tagged with which table their dates live in. Director/admin
--     only; returns nothing to anyone else.

alter table public.provider_away_dates
  add column if not exists entered_by uuid references public.users(id) on delete set null;
alter table public.fellow_away_dates
  add column if not exists entered_by uuid references public.users(id) on delete set null;

comment on column public.provider_away_dates.entered_by is
  'Who recorded this row. Null for rows predating the column, or equal to provider_id when self-entered.';
comment on column public.fellow_away_dates.entered_by is
  'Who recorded this row. Null for rows predating the column or generated by decide_vacation().';

create unique index if not exists fellow_away_dates_fellow_date_uniq
  on public.fellow_away_dates (fellow_id, away_date);

create or replace function public.stamp_entered_by()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  new.entered_by := coalesce(auth.uid(), new.entered_by);
  return new;
end;
$function$;

drop trigger if exists trg_stamp_entered_by on public.provider_away_dates;
create trigger trg_stamp_entered_by
  before insert or update on public.provider_away_dates
  for each row execute function public.stamp_entered_by();

drop trigger if exists trg_stamp_entered_by on public.fellow_away_dates;
create trigger trg_stamp_entered_by
  before insert or update on public.fellow_away_dates
  for each row execute function public.stamp_entered_by();

create or replace function public.away_people()
returns table(id uuid, full_name text, role text, source text)
language sql stable security definer set search_path = public as $$
  select u.id, u.full_name, u.role::text,
         case when u.role = 'fellow' then 'fellow' else 'provider' end as source
  from public.users u
  where u.status = 'active'
    and u.role in ('fellow', 'supervisor', 'director')
    and exists (
      select 1 from public.users me
      where me.id = auth.uid() and me.role in ('director', 'admin')
    )
  order by (u.role = 'fellow'), u.full_name;
$$;
revoke all on function public.away_people() from public;
grant execute on function public.away_people() to authenticated;

-- Supabase grants EXECUTE to anon by default on new functions in the public
-- schema, and "revoke ... from public" does not remove that explicit grant.
-- away_people() checks the caller is a director so anon got nothing anyway, but
-- list_supervisors() (added in 0004) has no such guard — before this an
-- unauthenticated caller could enumerate supervisor names.
revoke all on function public.away_people() from anon;
revoke all on function public.list_supervisors() from anon;
